* Palaver toolset

The goal of this project is to explore techniques for building components
of an LLM powered assistant tha uses a voice interface. The system is
being custom designed and built by the user for the exclusive use of
the user. The larger system architecture and goals are not relevant
to this project but are present in the mind of the user and will help
define the goals of this project.

None of the code in this project is expected to be preserved for a
long time without extensive modification or even replacement. The
goals of the project are indistinct and present only as a set
of mental images of future use present in the user's mind. 

With these facts in mind, there are no Product Requirements Documents
since there is no product, there is only "trying things out". 
There are no architectural guidance documents as they represent work that
will be wasted as the code undergoes massive changes when the user
decides to "try something else".

With those caveates in mind, the overall result of the code in this
project is to give the user a chance to experiment with the experince
of accomplishing specific tasks via a voice activated command system
with text to speech feedback.

** Current status

A basic structure has been built to allow the user to experiment with
voice activated note taking, and to start to differentiate the notes
based on command prefixes. The techniques uses are preliminary:

1. VAD based sound segment recording
2. Whisper.cpp file based segment transcription
3. Text collected into "drafts" based on detection of boundary phrases
4. Database storage of "drafts" (SqlModel/SQLAlchemy/Sqlite)
5. Websocket event streaming
6. A multi-server mechansim for listening to a microphone on one machine
   and doing transcription on another.
7. A "rescan" mechanism where one server uses the normal transcription
   tuning for responsiveness and a second uses better quality but
   slower transcription tuning. The rescan server listens to the
   "audio server" event stream and sends completed rescanned drafts
   to the audio server for storage.
8. A basic HTTP interface to stored "drafts"
9. A trivial HTMX UI


